name: Update Version and Database

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (eg: 0.19.435)'
        required: true
        default: '0.19.435'

jobs:
  update:
    name: branch - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      RDS_HOST: ${{ secrets.RDS_HOST }}
      BASTION_USER: ${{ secrets.BASTION_USER }}
      BASTION_HOST: ${{ secrets.BASTION_HOST }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Version File
      run: echo "${{ github.event.inputs.version }}" > .version
      shell: bash

    - name: Set up SSH key for bastion host
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}

    - name: SSH Tunnel to Bastion Host
      run: ssh -fNT -L 5432:${{ env.RDS_HOST }}:5432 ${{ env.BASTION_USER }}@${{ env.BASTION_HOST }}

    - name: Install PostgreSQL client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Run Update Queries

    - name: Run Update Queries
      run: |
        whcih psql
