name: SSH Tunnel

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (eg: 0.19.435)'
        required: true
        default: '0.19.435'

jobs:
  update_postgresql:
    name: branch - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update .version file & set key
      run: |
        echo "${{ github.event.inputs.version }}" > .version
        echo "${{ secrets.BASTION_SSH_PRIVATE_KEY }}" > bastion-key.pem
        sudo chmod 600 bastion-key.pem
        ls -lart


    - name: Update repo .version file
      uses: test-room-7/action-update-file@v1
      with:
        file-path: .version
        commit-msg: '[updated] .version file with ${{ github.event.inputs.version }}'
        branch: ${{ github.ref_name }}
        github-token: ${{ secrets.REPO_TOKEN }}
      

    - name: Setup SSH Tunnel
      run: |
        ssh -o StrictHostKeyChecking=no -i bastion-key.pem -f -N -L 5432:${{ secrets.RDS_HOST }}:5432 ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}
      
    - name: Run update query
      run: |
        IFS="." read -r V_MAJOR V_MINOR V_PATCH <<< ${{ github.event.inputs.version }}
        psql -h localhost -p 5432 -U ${{ POSTGRES_USER }} -d ${{ POSTGRES_DB }} -c "select * from t_app WHERE platform_version like '$V_MAJOR.$V_MINOR.%' order by created_at desc limit 10;"
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        
    - name: Clean up
      run: |
        rm -rf bastion-key.pem
        echo "All success.."
        
